name: master
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 5 1 * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: setup poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.2.2

      - name: install deps
        run: poetry install

      - name: build
        run: poetry run python main.py

      - name: publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./data
          publish_branch: build
